### ISSUE TITLE
Sorry, unrecognized username or password. Have you forgotten your password?

### ISSUE THREAD

**Issue by Fran-Uk** [folklabs/cpneighbours#1]
When logging into:  http://live-cpneighbours.pantheonsite.io/user/login  as "febnet02@btinternet.com"

Repeatedly asked 
"Sorry, unrecognized username or password. Have you forgotten your password?"

EVERY time logged out/return to website.

Workaround: request "Password Request", that allows: "You may now log in by clicking this link or copying and pasting it to your browser..."

Reset password to carry on a new session.

**Comment by pmackay** [comment]
Have you been able to resolve this now?

**Comment by Fran-Uk** [comment]
No

**Comment by pmackay** [comment]
Had you tried logging in with your username? I did some testing, that seemed ok, but it wasnt configured to allow logging in with email. However the message does not make that clear! Please try again now, have updated setting.

**Comment by Fran-Uk** [comment]
Thanks for looking into this.  Yes. Now aok. Works with email and with "Francis" user name.  

That's brill. Thanks.
