### ISSUE TITLE
Directory - Enter a location by pinning onto a map (instead of postcode)

### ISSUE THREAD

**Issue by Fran-Uk** [folklabs/cpneighbours#3]
Some locations, eg events in the park, need to be identified by pinning a point on a map, and post code is too crude a value, or not available.

Option to define a location as "pin on map" (or similar).

**Comment by pmackay** [comment]
This and other map issues will need looking at as part of the updates to mapping, which I'm planning to look into.

**Comment by pmackay** [comment]
Duplicate of https://github.com/folklabs/openlocal/issues/19.
