### ISSUE TITLE
Alerts

### ISSUE THREAD

**Issue by Fran-Uk** [folklabs/cpneighbours#4]
Cannot access the full alert from the home page.  Alerts allow adding description line and link field. But cannot access this info.

**Comment by pmackay** [comment]
If you add a description and link, can you see them on the homepage? Alerts have not been designed to have their own page.

**Comment by Fran-Uk** [comment]
Please can you log into the test system and check if you can add a new "alert".  

 Alerts allow adding description line and link field. But this info cannot be seen on the published view.  What is meant to be seen?

(This is hard for me to keep testing, as every time I log out I have to re-new my password.  Sometime this is quick, sometimes it is slow for the password reset email to be sent.)

**Comment by pmackay** [comment]
Apologies, I was thinking of the HH support. The theme on the CP Neighbours site is a copy from the Vassall site and we've not fully themed alerts for that theme yet. I've updated the example and added a link, which works, but the display of the Alert isnt quite what it should be yet.

**Comment by Fran-Uk** [comment]
Thanks. That makes sense. Yes. I can see the link now "works" when you click the alert.
